subscription:
    pattern:  /
    defaults: { _controller: "NewsBundle:Subscription:index" }

subscription_show:
    pattern:  /{id}/show
    defaults: { _controller: "NewsBundle:Subscription:show" }

subscription_new:
    pattern:  /new
    defaults: { _controller: "NewsBundle:Subscription:new" }

subscription_create:
    pattern:  /create
    defaults: { _controller: "NewsBundle:Subscription:create" }
    requirements: { _method: post }

subscription_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "NewsBundle:Subscription:edit" }

subscription_update:
    pattern:  /{id}/update
    defaults: { _controller: "NewsBundle:Subscription:update" }
    requirements: { _method: post|put }

subscription_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "NewsBundle:Subscription:delete" }
    requirements: { _method: post|delete }
