user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: UserBundle:Default:index }


user_login:
    pattern: /login
    defaults: { _controller: UserBundle:Default:login }

user_crud:
    resource: "@UserBundle/Resources/config/routing/user.yml"
    prefix:   /
