HW3\UserBundle\Entity\User:
    properties:
        id:
            - NotNull: ~
        firstname:
            - NotBlank: ~
            - MinLength: 3
            - MaxLength: 255
        lastname:
            - NotBlank: ~
            - MinLength: 3
            - MaxLength: 255
        username:
            - NotBlank: ~
            - MinLength: 3
            - MaxLength: 255
        showname:
            - NotBlank: ~
            - MinLength: 3
            - MaxLength: 255
        password:
            - NotBlank: ~
            - MinLength: 3
            - MaxLength: 255
