HW3\UserBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
    properties:
        firstname:
            - NotBlank: ~
            - Length:
                min: 3
                max: 255
        lastname:
            - NotBlank: ~
            - Length:
                min: 3
                max: 255
        username:
            - NotBlank: ~
            - Length:
                min: 3
                max: 255
        creation_date:
            - DateTime: ~
        showname:
            - NotBlank: ~
            - Length:
                min: 3
                max: 255
        password:
            - NotBlank: ~
        newsgroups:
            - Count:
                min: 0
                max: 3