comment:
    resource: "@CommentBundle/Resources/config/routing.yml"
    prefix:   /comment/

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user/

news:
    resource: "@NewsBundle/Resources/config/routing.yml"
    prefix: /news/

login:
    pattern: /login
    defaults: {_controller: UserBundle:Default:login}

logout:
    path: /logout

login_check:
    pattern: /login_check
