comment:
    resource: "@CommentBundle/Resources/config/routing.yml"
    prefix:   /comment/

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user/

news:
    resource: "@NewsBundle/Resources/config/routing.yml"
    prefix: /news/

