comment:
    resource: "@CommentBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/comment/
    defaults: {_locale: fa}
    requirements:
        _locale: en|fa

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/user/
    defaults: {_locale: fa}
    requirements:
        _locale: en|fa

login:
    pattern: /{_locale}/user/login
    defaults: {_controller: UserBundle:Default:login, _locale: fa}
    requirements:
        _locale: en|fa

logout:
    path: /{_locale}/user/logout

login_check:
    pattern: /{_locale}/user/login_check

news:
    resource: "@NewsBundle/Resources/config/routing.yml"
    prefix: /{_locale}/
    defaults: {_locale: fa}
    requirements:
        _locale: en|fa
