comment:
    resource: "@CommentBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/comment/
    defaults: {_locale: fa}
    requirements:
        _locale: en|fa

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/user/
    defaults: {_locale: fa}
    requirements:
        _locale: en|fa


news:
    resource: "@NewsBundle/Resources/config/routing.yml"
    prefix: /{_locale}/news/
    defaults: {_locale: fa}
    requirements:
        _locale: en|fa

login:
    pattern: /{_locale}/login
    defaults: {_controller: UserBundle:Default:login, _locale: fa}
    requirements:
        _locale: en|fa

logout:
    path: /logout

login_check:
    pattern: /login_check
