HW3\NewsBundle\Entity\News:
    type: entity
    table: null
    repositoryClass: HW3\NewsBundle\Entity\NewsRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        title:
            type: string
            length: '255'
        abstract:
            type: text
        image:
            type: string
            length: '511'
        datetime:
            type: datetime
        content:
            type: text
        visit:
            type: integer
    manyToOne:
        user:
            targetEntity: HW3\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
        newsgroup:
            targetEntity: NewsGroup
            joinColumn:
                name: newsgroup_id
                referencedColumnName: id
    oneToMany:
        comments:
            targetEntity: HW3\CommentBundle\Entity\Comment
            mappedBy: news
    properties:
        id:
            - NotNull: ~
        title:
            - NotBlank: ~
            - MaxLength: 255
        abstract:
            - NotBlank: ~
        image:
            - NotBlank: ~
            - Image:
                minWidth: 1
                minHeight: 1
        datetime:
            - DateTime: ~
        content:
            - NotBlank: ~
        visit:
            - NotBlank: ~
            - Min: 0
    lifecycleCallbacks: {  }
