HW3\NewsBundle\Entity\Subscription:
    type: entity
    table: subscription
    repositoryClass: HW3\NewsBundle\Entity\SubscriptionRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

        email:
            type: string
            length: '255'

    manyToOne:
        newsgroup:
            targetEntity: HW3\NewsBundle\Entity\NewsGroup
            inversedBy: subcriptions
            joinColumn:
                name: newsgroup_id
                referencedColumnName: id

    lifecycleCallbacks: {  }
