HW3\NewsBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: HW3\NewsBundle\Entity\UserRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        firstname:
            type: string
            length: '127'
        lastname:
            type: string
            length: '127'
        username:
            type: string
            length: '127'
        password:
            type: string
            length: '127'
        showname:
            type: string
            length: '127'
    lifecycleCallbacks: {  }
