news_homepage:
    pattern:  /home
    defaults: { _controller: NewsBundle:Default:home }

news_header:
    pattern: /header
    defaults: { _controller: NewsBundle:Default:header }

news_category:
    pattern: /category/{id}
    defaults: { _controller: NewsBundle:Default:category}

news_single:
    pattern: /news/{id}
    defaults: { _controller: NewsBundle:Default:single }

news_ajax:
    pattern: /ajax
    defaults: { _controller: NewsBundle:Default:ajax }

news_search:
    pattern: /news/search
    defaults: { _controller: NewsBundle:Default:search}

news_crud:
    resource: "@NewsBundle/Resources/config/routing/news.yml"
    prefix:   /user/news

newsgroup_crud:
    resource: "@NewsBundle/Resources/config/routing/newsgroup.yml"
    prefix:   /user/news/newsgroup