news_homepage:
    pattern:  /home
    defaults: { _controller: NewsBundle:Default:home }

news_header:
    pattern: /header
    defaults: { _controller: NewsBundle:Default:header }

news_category:
    pattern: /category/{id}/{page}
    defaults: { _controller: NewsBundle:Default:category, page: 1}

news_ajax:
    pattern: /ajax
    defaults: { _controller: NewsBundle:Default:ajax }

news_search:
    pattern: /news/search/{page}
    defaults: { _controller: NewsBundle:Default:search, page: 1}

news_rss:
    pattern: /news/rss/{page}
    defaults: { _controller: NewsBundle:Default:RSS, page: 1}

news_single:
    pattern: /news/{id}
    defaults: { _controller: NewsBundle:Default:single }

news_crud:
    resource: "@NewsBundle/Resources/config/routing/news.yml"
    prefix:   /user/news

newsgroup_crud:
    resource: "@NewsBundle/Resources/config/routing/newsgroup.yml"
    prefix:   /user/news/newsgroup

subscription_crud:
    resource: "@NewsBundle/Resources/config/routing/subscription.yml"
    prefix:   /user/subscription

tag_crud:
    resource: "@NewsBundle/Resources/config/routing/tag.yml"
    prefix:   /user/tag
