# src/HW3/NewsBundle/Resources/config/validation.yml
HW3\NewsBundle\Entity\News:
    properties:
        title:
            - NotBlank:
                message: Please enter title.
            - Length:
                max: 255
                maxMessage: Title should be at most {{ limit }} charachter.
        abstract:
            - NotBlank:
                message: Please enter abstract.
        image:
            - NotBlank:
                message: Please select image uri.
            - Image:
                mimeTypesMessage: Please select an image.
                maxSizeMessage: The file is too large. Allowed maximum size is {{ limit }}
        creation_date:
            - DateTime: ~
        content:
            - NotBlank:
                message: Please enter content.
        visit:
            - NotBlank: ~
            - Range:
                min: 0
        confirmed:
            - NotBlank: ~
        user:
            - NotNull: ~
        newsgroup:
            - NotNull: ~
        tags:
            - Count:
                min: 0
                max: 10

HW3\NewsBundle\Entity\NewsGroup:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: name
            message: Newsgroup with this name already exists.
    properties:
        name:
            - NotBlank:
                message: Please enter name of the news group.
            - Length:
                min: 3
                max: 255
                minMessage: Name should has more than {{ limit - 1 }} character.
                maxMessage: Name should has less than {{ limit + 1 }} character.
        creation_date:
            - DateTime: ~

        level:
            - NotBlank:
                message: Please enter importance level of the group.
            - Range:
                min: 0
                minMessage: Level should be possitive integer.

HW3\NewsBundle\Entity\Subscription:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email, newsgroup_id]
            message: This Subscription already exists.
    properties:
        email:
            - NotBlank:
                message: Please enter your email.
            - Email:
                message: The email "{{ value }}" is not a valid email.

        newsgroup:
            - NotNull: ~

HW3\NewsBundle\Entity\Tag:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: name
            message: Tag with this name already exists.
    properties:
        name:
            - NotBlank:
                message: Please enter proper name.
