# src/HW3/NewsBundle/Resources/config/validation.yml
HW3\NewsBundle\Entity\News:
    properties:
        title:
            - NotBlank: ~
            - Length:
                max: 255
        abstract:
            - NotBlank: ~
        image:
            - NotBlank: ~
            - Image:
                minWidth: 1
                minHeight: 1
        creation_date:
            - DateTime: ~
        content:
            - NotBlank: ~
        visit:
            - NotBlank: ~
            - Range:
                min: 0
        user:
            - NotNull: ~
        newsgroup:
            - NotNull: ~

HW3\NewsBundle\Entity\NewsGroup:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
                max: 255
        creation_date:
            - DateTime: ~

        level:
            - NotBlank: ~
            - Range:
                min: 0

        users:
            - Count:
                min: 0