# src/HW3/NewsBundle/Resources/config/validation.yml
HW3\NewsBundle\Entity\News:
    properties:
        title:
            - NotBlank:
                message: Please enter title.
            - Length:
                max: 255
                maxMessage: Title should be at most 255 charachter.
        abstract:
            - NotBlank:
                message: Please enter abstract.
        image:
            - NotBlank:
                message: Please enter image uri.
            - Image: ~
        creation_date:
            - DateTime: ~
        content:
            - NotBlank:
                message: Please enter content.
        visit:
            - NotBlank: ~
            - Range:
                min: 0
        user:
            - NotNull: ~
        newsgroup:
            - NotNull: ~

HW3\NewsBundle\Entity\NewsGroup:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
                max: 255
        creation_date:
            - DateTime: ~

        level:
            - NotBlank: ~
            - Range:
                min: 0

        users:
            - Count:
                min: 0