comment_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: CommentBundle:Default:index }

comment_crud:
    resource: "@CommentBundle/Resources/config/routing/comment.yml"
    prefix:   /comment