HW3\CommentBundle\Entity\Comment:
    properties:
        composer:
            - NotBlank:
                message: Please enter your name.
            - Length:
                max: 255
                maxMessage: Your name should have at most {{ limit }} charachter.
        content:
            - NotBlank:
                message: Please enter your comment content.
            - Length:
                max: 8192
                maxMessage: Your comment should have at most {{ limit }} character.
        creation_date:
            - DateTime: ~
        pos:
            - NotBlank: ~
            - Range:
                min: 0
        neg:
            - NotBlank: ~
            - Range:
                min: 0
        level:
            - NotBlank: ~
            - Range:
                min: 0
        news:
            - NotBlank: ~