HW3\CommentBundle\Entity\Comment:
    properties:
        composer:
            - NotBlank: ~
            - Length:
                min: 3
                max: 255
        content:
            - NotBlank: ~
            - Length:
                max: 8192
        creation_date:
            - DateTime: ~
        pos:
            - NotBlank: ~
            - Range:
                min: 0
        neg:
            - NotBlank: ~
            - Range:
                min: 0
        news:
            - NotBlank: ~