HW3\UserBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: HW3\UserBundle\Entity\UserRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        firstname:
            type: string
            length: '255'
        lastname:
            type: string
            length: '255'
        username:
            type: string
            length: '255'
        userpwd:
            type: string
            length: '255'
        showname:
            type: string
            length: '255'
        creationDateTime:
            type: datetime
    manyToMany:
        newsgroups:
            targetEntity: HW3\NewsBundle\Entity\NewsGroup
            inversedBy: users
            joinTable:
                name: usernewsgroup
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
