<?php

namespace HW3\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsGroupRepository extends EntityRepository
{
}
