<?php

namespace HW3\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    function getNewsFromGroup($group, $from, $limit)
    {
        return $this->findBy(array(
            'newsgroup' => $group
        ), array(
            'creation_date' => 'ASC',
        ), $limit, $from);
    }

    function getNewsCount($group)
    {
        return count($this->findBy(array(
            'newsgroup' => $group
        )));
    }
}