<?php

namespace HW3\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    function getNewsFromGroup($group, $from, $limit)
    {
        return $this->findBy(array(
            'newsgroup' => $group
        ), array(
            'creation_date' => 'DESC',
        ), $limit, $from);
    }

    function getNewsCount($group)
    {
        return count($this->findBy(array(
            'newsgroup' => $group
        )));
    }

    function getHotNews($limit)
    {
        $db = $this->createQueryBuilder('n')
            ->where('n.creation_date > :date')
            ->setParameter('date', new \DateTime('yesterday'))
            ->addOrderBy('n.visit', 'DESC')
            ->addOrderBy('n.creation_date', 'DESC')
            ->setMaxResults($limit);
        return $db->getQuery()->getResult();
    }

    function getRecentNews($limit)
    {
        $db = $this->createQueryBuilder('n')
            ->addOrderBy('n.creation_date', 'DESC')
            ->setMaxResults($limit);
        return $db->getQuery()->getResult();
    }
}