<?php

namespace HW3\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * tagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
}
